version: '3.9'

services:
  service1:
    build:
      context: ./service_1
    ports:
      - "8001:8001"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  service2:
    build:
      context: ./service_2
    ports:
      - "8002:8002"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - service1
      - service2
    networks:
      - backend

networks:
  backend:
    driver: bridge
